### ISSUE TITLE
The footer section

### ISSUE THREAD

**Issue by AM-77** [hexojs/site#1042]
The footer section hides the aside section in the documentation pages
![Screenshot from 2019-08-17 23-21-39](https://user-images.githubusercontent.com/18232579/63217507-a6653480-c147-11e9-8451-5959fe74ceeb.png)
.

**Comment by curbengh** [comment]
I can confirm this issue.

carbonads follows scrolling and drags along the table of content (toc). Without the ads, the toc will not follow scrolling.

The expected behavior is that carbonads should stop pushing down toc when the bottom of toc reaches the footer section.

This issue doesn't affect desktop screen; to reproduce in desktop, resize it less than half height.
