### ISSUE TITLE
main-nav does not work recently

### ISSUE THREAD

**Issue by gaoming714** [hexojs/site#1170]
navbar does not work on my site.
here is the HTML code  on my Firefox.    

> `<nav id="main-nav">`
> missing the Docs API News Plugins Themes

>    ` <a href="https://github.com/hexojs/hexo" rel="external nofollow noreferrer" class="main-nav-link"><i class="fa fa-github-alt"></i></a>
>     <div id="search-input-wrap" class="on">
>     <div id="search-input-icon">`

**Comment by curbengh** [comment]
Sorry about that, fixed in https://github.com/hexojs/site/pull/1173.

**Comment by gaoming714** [comment]
Perfect fix, but I have two questions about this issue.

Is it because agile development (rolling updates),which is causing such an issue that occasionally occurs? 

Should I raise it the next time I encounter a small flaw? 
Or wait a little bit for your fix. I know you're fixing fast.

**Comment by curbengh** [comment]
We are indeed using continuous deployment, any commit made to the master branch of this repo is pushed to the website.

Before we merge the commit, we usually do the following:
1. Code review
2. Preview in localhost (if the change is significant)
3. Check deploy preview

This issue is stemmed from https://github.com/hexojs/site/pull/1139, which @SukkaW and I  did performed local test, but we both forgot to check the [deploy preview](https://deploy-preview-1173--hexo-site.netlify.com/).

Aside from that mistake, another cause is that Netlify is very conservative on updating the hexo package that is sourced from the [repo](https://github.com/hexojs/hexo) (instead of the usual npmjs), we want to use the latest commit of hexo package. We've only [discovered](https://github.com/hexojs/site/pull/1102) this limitation recently.

We're currently exploring a few options to mitigate the limitation.

We do appreciate if you can let us know if similar issue comes up next time.
