### ISSUE TITLE
Wrong config.keywords description

### ISSUE THREAD

**Issue by noraj** [hexojs/site#1286]
## Issue

[`config.keywords`](https://hexo.io/docs/configuration) says to separate keywords with a comma but that's not the right way.

## Context

To showcase I will use a list of tags with Bulma CSS framework and a pug template.

pug snippet:

```pug
        div(class="tags")
          each tag in config.keywords
            span(class="tag")
              = tag
```

## Case 1

_config.yml

```yaml
keywords: documentation, markdown, custom, staticgen
```

![image](https://user-images.githubusercontent.com/16578570/72305111-01f20a80-3673-11ea-807a-a22e88109f3e.png)

## Case 2

_config.yml

```
keywords:
  - documentation
  - markdown
  - custom
  - staticgen
```

or

```yaml
keywords: [documentation, markdown, custom, staticgen]
```

![image](https://user-images.githubusercontent.com/16578570/72305087-f56db200-3672-11ea-8d66-4aa2f4c224c1.png)

## Solution

In fact a valid YAML array of string is expect and not a string with keywords separated by commas.

## PR

I'll do a PR very soon.

**Comment by curbengh** [comment]
the "config.keywords" is mainly for open_graph helper which supports both string and array type.
if the config is a string, it will [convert](https://github.com/hexojs/hexo/blob/4b061cbd6badf19782490b3308478d6ffe3fc7a6/lib/plugins/helper/open_graph.js#L138) to an array, but it doesn't modify the original config.

I suggest your pug template to support both string and array types.

**Comment by noraj** [comment]
@curbengh But when using a string containing words separated by commas which is automatically  converted to an array, as you can see in `Case 1` each char is split instead of each word. So you mean I have to detect in my template if an array or a string is provided and parse it accordingly like open_graph ?

**Comment by curbengh** [comment]
> So you mean I have to detect in my template if an array or a string is provided and parse it accordingly like open_graph

It depends whether you intend to publish your theme. If it's intended for the public, then your users most probably would specify `keywords` as a comma-separated string.

I do agree `keywords` shouldn't support comma-separated string in the first place, I guess it supports string because the resulting `keywords` meta tag is indeed a comma-separated string.

However, since `keywords` meta tag has been dropped in https://github.com/hexojs/hexo/pull/3805, it's no longer useful to specify `keywords` as a comma-separated string. I'll bring this up in hexo.
